const express=require("express")
const usermodel=require("../model/userSchema")
const userController=require("../controller/userController")
const {uservalidate,verifytoken}=require("../middleware/user")
const userRouter=express()
userRouter.post("/add",uservalidate,userController.newuser)
userRouter.get("/list",userController.userlist)
userRouter.post("/update",uservalidate,userController.userUpdate)
userRouter.get("/get/:id",userController.userGetUpdate)
userRouter.get("/delete/:id",userController.userdelete)
userRouter.post("/login",userController.userlogin)
module.exports=userRouter